title: Fariha Hoque Mimma
logo: /assets/image/Fariha_hoque_mimma.jpg
Description: I am an aspiring software quality assurance engineer with a fresh perspective and a hunger to make a meaningful impact in the industry.
show_downloads: false
theme: jekyll-theme-cayman
